include:
  - project: 'IsyFact/isy-gitlabci-templates'
    file: '/maven/.gitlab-ci-maven.yml'

pages:
  stage: deploy
  script:
    - echo 'Deploy isyfact documentation'
  artifacts:
    paths:
    - public
  only:
  - gh-pages