name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with Git LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Remove Git LFS
        run: |
          rm .gitattributes
          git lfs uninstall

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: .