name: prepare_playbook.yml
on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_repo:
        description: 'If called by a pull request: repository the pull request belongs to'
      pr_branch:
        description: 'If called by a pull request: branch which should be merged'
      pr_target:
        description: 'If called by a pull request: branch which should be merged into'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          echo "github.repository = ${{ github.repository }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"

      - name: Checkout playbook
        uses: actions/checkout@v4

      - name: Prepare playbook
        uses: mikefarah/yq@master
        with:
          cmd: yq '.content.sources[]' 'antora-playbook.yml'
