name: prepare_playbook.yml
on:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_repo:
        description: 'If called by a pull request: repository the pull request belongs to'
      pr_branch:
        description: 'If called by a pull request: branch which should be merged'
      pr_target:
        description: 'If called by a pull request: branch which should be merged into'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        run: |
          echo "github.repository = ${{ github.repository }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          
          repo_name="${{ github.repository }}"
          echo "CONTENT_SOURCE_NAME=isy-standards" >> $GITHUB_ENV
          echo "CONTENT_SOURCE_BRANCH=release/3.x" >> $GITHUB_ENV
          echo "PR_REF=${{ github.ref }}" >> $GITHUB_ENV

      - name: Checkout playbook
        uses: actions/checkout@v4

      - name: Check if PR target branch is part of the online documentation
        id: search-pr-target-branch
        # if this command returns an empty result (outputs.result), the PRs target branch isn't part of the online documentation.
        uses: mikefarah/yq@master
        with:
          cmd: yq '(.content.sources[] | select(.url == "./${{ env.CONTENT_SOURCE_NAME }}*" and .branches == "${{ env.CONTENT_SOURCE_BRANCH }}"))' 'antora-playbook.yml'

      - name: Replace PR target branch with the PR branch
        id: replace-pr-target-branch
        if: ${{ steps.search-pr-target-branch.outputs.result != ''}} # only run if the step before found anything
        uses: mikefarah/yq@master
        with:
          cmd: yq -i 'with(.content.sources[] | select(.url == "./${{ env.CONTENT_SOURCE_NAME }}*" and .branches == "${{ env.CONTENT_SOURCE_BRANCH }}"); .url = "./pull-request" | .branches = "${{ env.PR_REF }}")' antora-playbook.yml

      - name: Show updated playbook
        run: cat antora-playbook.yml
